### ISSUE TITLE
The difference in accuracy is too large for different random seeds

### ISSUE THREAD

**Issue by ydxswys1** [hongyizhi/TSFCNet#1]
大佬，请问你有没有发现随机种子不同，在2a那个数据集上跨session（ho）同一个被试的精度差距有点大，我在我的电脑上跑了一下有些被试随机种子不同精度都有可能差距3-5.预处理是按你给的代码做的。模型以及训练代码没改。这个是正常的吗？数据集太小，这个是正常的吗？

**Comment by hongyizhi** [comment]
影响精度的因素有很多
1.整个环境的版本，包括pytorch和scipy.signal，包括运行设备等
2.同一个被试精度可能有差距，但是整个数据集平均下来应该是差不多的。正常误差可能只是百分之2左右，这是我做实验的经验
